const songs = [
  { number: 1, title: "Balya Baana babalagu", lyrics: `Song 1 lyrics here...` },
  { number: 2, title: "Ku nguba hali kaaya kiija", lyrics: `Song 2 lyrics here...` },
  { number: 3, title: "Kolera Mungu mukolwa", lyrics: `Song 3 lyrics here...` },
  { number: 4, title: "Nyiijibanire nya magene miingi", lyrics: `Song 4 lyrics here...` },
  { number: 5, title: "Tanganika mu katikati", lyrics: `Song 5 lyrics here...` },
  { number: 6, title: "Mungu akulozize", lyrics: `Song 6 lyrics here...` },
  { number: 7, title: "Kobeka lwa kabuungo", lyrics: `Song 7 lyrics here...` },
  { number: 8, title: "Balya bemeezire Mwaazi gwaage Kuunu", lyrics: `Song 8 lyrics here...` },
  { number: 9, title: "Mukiza waani lo lwaala lwiija", lyrics: `Song 9 lyrics here...` },
  { number: 10, title: "Yesu nya kuheeza byooshi", lyrics: `Song 10 lyrics here...` },

  { number: 11, title: "Wee! Mulaazi twabuuza", lyrics: `Song 11 lyrics here...` },
  { number: 12, title: "Yee, Mukiza mwiija ngweete", lyrics: `Song 12 lyrics here...` },
  { number: 13, title: "Bushigi lyo baaligwata Yesu", lyrics: `Song 13 lyrics here...` },
  { number: 14, title: "Sayuni waangirire Nahamweenu", lyrics: `Song 14 lyrics here...` },
  { number: 15, title: "Kalamo ko ngweete mu mutima gwaani", lyrics: `Song 15 lyrics here...` },
  { number: 16, title: "Iri utaanga bikirira bweneene", lyrics: `Song 16 lyrics here...` },
  { number: 17, title: "Bulamu bwa muno mu kihugo", lyrics: `Song 17 lyrics here...` },
  { number: 18, title: "Wiije imwa Yesu", lyrics: `Song 18 lyrics here...` },
  { number: 19, title: "Siku zikola niini", lyrics: `Song 19 lyrics here...` },
  { number: 20, title: "Ko Mungu akegira kutalusire bweenge", lyrics: `Song 20 lyrics here...` },

  { number: 21, title: "Mwiira waani, ndania zaabe uzibiike imwa Yesu", lyrics: `Song 21 lyrics here...` },
  { number: 22, title: "Iri waanga luha mu lugeendo", lyrics: `Song 22 lyrics here...` },
  { number: 23, title: "Ku mukyo kuziinduka lusiku", lyrics: `Song 23 lyrics here...` },
  { number: 24, title: "Kuunu, muliro gwaabe tutumire", lyrics: `Song 24 lyrics here...` },
  { number: 25, title: "Shooko yu lwiiji ikiri kuulya", lyrics: `Song 25 lyrics here...` },
  { number: 26, title: "Twa mubiika mwa maboko gaabe uno mwaana", lyrics: `Song 26 lyrics here...` },
  { number: 27, title: "Nyanya geenda hale bweneene", lyrics: `Song 27 lyrics here...` },
  { number: 28, title: "Biki byo nyaangooboha kizizi", lyrics: `Song 28 lyrics here...` },
  { number: 29, title: "Iryaba agabutwa Yesu", lyrics: `Song 29 lyrics here...` },
  { number: 30, title: "Twiimbire Mukiza weetu Yesu Kristo", lyrics: `Song 30 lyrics here...` },

  { number: 31, title: "Mutima gwaani usiimage bwiija", lyrics: `Song 31 lyrics here...` },
  { number: 32, title: "Yesu Rukiza akubuuza ku lukogo", lyrics: `Song 32 lyrics here...` },
  { number: 33, title: "Wootage nyaani mwiira ikizizi kiija", lyrics: `Song 33 lyrics here...` },
  { number: 34, title: "Shaaga imwa Yesu Rukiza", lyrics: `Song 34 lyrics here...` },
  { number: 35, title: "Akambwikira ndaagakifa kaandi", lyrics: `Song 35 lyrics here...` },
  { number: 36, title: "Nyiri nya mageni miingi", lyrics: `Song 36 lyrics here...` },
  { number: 37, title: "Iyo shiba nyayo igalaka baandu", lyrics: `Song 37 lyrics here...` },
  { number: 38, title: "Twe baandu bashwekwiirwe", lyrics: `Song 38 lyrics here...` },
  { number: 39, title: "Muko gwaabe gwi migashaaniro", lyrics: `Song 39 lyrics here...` },
  { number: 40, title: "Nyahamweetu Mungu wi myakuula", lyrics: `Song 40 lyrics here...` },

  { number: 41, title: "Yesu, wu lukogo lwiingi", lyrics: `Song 41 lyrics here...` },
  { number: 42, title: "Kiziki kikiri mu buhya", lyrics: `Song 42 lyrics here...` },
  { number: 43, title: "Naama yu muundu ulya wemeezire Mungu", lyrics: `Song 43 lyrics here...` },
  { number: 44, title: "Hahe tugabona ubwiija bu mutima", lyrics: `Song 44 lyrics here...` },
  { number: 45, title: "Mungu umbuuze imwaabe", lyrics: `Song 45 lyrics here...` },
  { number: 46, title: "Tulangiize iyo muunda", lyrics: `Song 46 lyrics here...` },
  { number: 47, title: "Utume mutima gwaabe", lyrics: `Song 47 lyrics here...` },
  { number: 48, title: "Nga nyi shooko ya meeji miija", lyrics: `Song 48 lyrics here...` },
  { number: 49, title: "Eh Yesu, ndangiibagira", lyrics: `Song 49 lyrics here...` },
  { number: 50, title: "Lo lwiiji luli lu muko", lyrics: `Song 50 lyrics here...` },

  { number: 51, title: "Lukogo lwa Mungu luneene", lyrics: `Song 51 lyrics here...` },
  { number: 52, title: "Iizu liguma likambuliiza", lyrics: `Song 52 lyrics here...` },
  { number: 53, title: "Ziri Naama kubonaana na Yesu", lyrics: `Song 53 lyrics here...` },
  { number: 54, title: "Israeli baage Mungu", lyrics: `Song 54 lyrics here...` },
  { number: 55, title: "Kihugo kiija kya tuliinda iyo", lyrics: `Song 55 lyrics here...` },
  { number: 56, title: "Nie Mwaana ngiri Lugata", lyrics: `Song 56 lyrics here...` }
];